### ISSUE TITLE
Subsequent P2P exceeding 100%

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#2341] opened 2023-05-11 14:31 UTC
App:  https://github.com/opensrp/fhircore/releases/tag/v0.2.3-rc1
Device : G60 3GB RAM 64GB ROM android 9
App ID: `CHA`, `CHSS`
**Describe the bug**
- when sending data via p2p in subsequent times, the percentage is exceeding 100%. See video below.

https://github.com/opensrp/fhircore/assets/84722169/c89e92bb-1606-4cde-a872-27a82dafda33

added data  Household: `Karimi`, Family members: `Williams, bear`
Careplans: `Family planning`

**To Reproduce**
- login to one device with `CHA`
- login to another device with `CHSS` 
- ensure sync is completed on both devices.
- add some data on the `CHA` device e.g add a HH and register members and enroll them to a careplan
- initialize the p2p transfer.
- after its complete. Disconnect the 2 devices.
- Add records on the CHA device. 
- Try P2P again and observe.

**Expected behavior**
- [ ] P2P should never go beyond 100%. 
- [ ] The % should show how many of any new records since last p2p have been transferred. 
- [ ] 100% shows a complete p2p and all records have been transferred from one device to another.

**Comment by ekigamba** [comment] 2023-05-15 12:40
The issue is a big  complicated due to a design flaw. The `_lastUpdated` which is used is not unique and therefore we have multiple records with the same `_lastUpdated`  of the same resource type.

This means we have a numbers of cases where we can either ignore records by assuming that the next subsequent send should only fetch records whose `_lastUpdated` is >. The `lastUpdated` when fetched from the server can also be behind and it's never updated during insertion into the DB, this means we might miss some records during p2p sync that were synced from the server

We can try and fix the specific issues or change the initial design to so we have some sort of rowId that is unique and increments for new records and updates

**Comment by madrinekariuki** [comment] 2023-06-30 12:39
@AnnieMungai 
https://github.com/opensrp/fhircore/releases/v0.2.4-rc1
Device : `android 11` &` android 9`
App ID: `cha`

This Fails QA. 
- P2P sync still exceeds 100%
- This is now happening even on the initial sync. see below video (on subsequent sync)and screenshot(from initial sync)

![image](https://github.com/opensrp/fhircore/assets/84722169/4eea686a-2ef9-4ebb-9be9-4100a8f411af)

https://github.com/opensrp/fhircore/assets/84722169/40728775-dd10-4bf7-9b3b-0e122193d85f

**Comment by pld** [comment] 2023-06-30 14:30
@ekigamba I would first check if this is indicative of a problem with records not being synced, if it is then we need to investigate deeply. If it's not, all records are being synced but for some reason the percent is >100, we can add a max on the percent as a stop-gap, then do a deeper investigation to make the percent more accurate

**Comment by ekigamba** [comment] 2023-07-03 16:15
@pld  I agree. I also noticed that the p2p version being used is outdated

**Comment by pld** [comment] 2023-07-05 16:24
closing this, please reopen if we see it not working on the main branch

**Comment by ekigamba** [comment] 2023-07-06 09:48
From my investigations, the total number of records sent via p2p sync are more than what is available on the database and therefore there might be some duplicate records being sent to the receiving device. This issue was replicated on the first p2p sync and not on the subsequent syncs. 

:disappointed: This seems to be a regression caused when the p2p version updated [here](https://github.com/opensrp/fhircore/pull/2526/files) was changed back to 0.6.3. However, the library code traversed from FHIR Core seems to some of the interface params added to fix this :man_shrugging: . I'll be retesting the app by syncing afresh to confirm the bug no longer exists. The new changes to indexes do not have proper migrations and therefore the app crashes without a fresh install and sync.

**Comment by madrinekariuki** [comment] 2023-07-10 10:54
@AnnieMungai 
https://github.com/opensrp/fhircore/releases/tag/v0.2.4-rc3

- This passes QA.

**Closed** 2023-07-10 10:54 UTC
Labels: Bug Report, Priority - High, Error-Handling, QA+
