### ISSUE TITLE
Quest/G6PD - Patient Registration record is not saving and app crashing when we select AGE instead of DOB

### ISSUE THREAD

**Issue by shoaibmushtaq25** [opensrp/fhircore#903] opened 2021-12-27 08:48 UTC
**Describe the bug**
Patient Registration record is not saving and app crashing when we select AGE instead of DOB

**To Reproduce**
1. Go to 'Home Screen' on Quest and G6PD App
2. Click on 'Register New Patient'
3. Fill out all necessary data of Patient and select AGE instead of DOB
3. Scroll down and Save Patient Registration Questionnaire

**Expected behavior**
App shouldn't crash and be able to transform the age to proper DOB with structure map transformation

**Screenshots**
![Screenshot_1640594828](https://user-images.githubusercontent.com/12672919/147453651-6f3890f1-8e43-46f5-a849-0f9c8165f77c.png)

**Smartphone (please complete the following information):**
- Device: Pixel 3 API 30 emulator
- Android version: 11
- Build number: RSR1.201013.001
- Version: 30 

**Additional context**
Stack trace is here,

`2021-12-27 13:39:41.538 10594-10594/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 10594
    org.hl7.fhir.exceptions.FHIRException: Exception executing transform patient.birthDate = evaluate(item_age"today() - $this.answer.value") on Rule "r_p_age": Error performing -: left and right operand have incompatible or illegal types (date, decimal) (@char 3)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1958)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1829)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1416)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1420)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeDependency(StructureMapUtilities.java:1462)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1424)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1377)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByStructureMap(ResourceMapper.kt:172)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.access$extractByStructureMap(ResourceMapper.kt:77)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper$extractByStructureMap$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.hl7.fhir.exceptions.PathEngineException: Error performing -: left and right operand have incompatible or illegal types (date, decimal) (@char 3)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.opMinus(FHIRPathEngine.java:2236)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1432)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1189)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:542)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1888)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1829) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1416) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1420) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeDependency(StructureMapUtilities.java:1462) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1424) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1377) 
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByStructureMap(ResourceMapper.kt:172) 
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.access$extractByStructureMap(ResourceMapper.kt:77) 
        at com.google.android.fhir.datacapture.mapping.ResourceMapper$extractByStructureMap$1.invokeSuspend(Unknown Source:18) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by mwkhan1983** [comment] 2021-12-29 11:27
closing because this is the duplicate of #876

**Closed by mwkhan1983** 2021-12-29 11:27 UTC
Labels: bug

**Comment by ekigamba** [comment] 2021-12-29 12:31
@shoaibmushtaq25 Thanks for clearly describing the issue and noticing that it was a duplicate
