### ISSUE TITLE
The app shows a "Sync Complete" toaster even if sync failed

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2575] opened 2023-07-12 11:35 UTC
**Describe the bug**
- Currently, the application would emit a _Sync Complete_ toaster even if the sync didn't complete successfully. 
- This is confusing to the users and might lead to data loss in case users deleted the app based on the toaster. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Application
2. Generate some invalid data that can't sync to the server. 
3. Click on the sync icon 
4. Wait and see the response after it fails

**Expected behaviour**
- [ ] _Sync Complete_ Should only be emitted if all the required data has been synced to and from the sync.

**Comment by ndegwamartin** [comment] 2023-07-12 11:58
Is this what we'd want for all our clients or does it need to be configurable? I think we might need to discuss/define what happens for the UX for this context.

For context, the sync implementation is such that sync is carried out per endpoint/resource. That means e.g. if we start with the _Patient_ resources we will save all the Patient records then move on to the next resource e.g. _Encounters_.

Assuming the following configuration for endpoints where we have _Patients_ then _Encounters_ then _Observations_ , what should happen to _Observations_ when syncing the _Encounters_ fails?

Secondly, for Sync Complete status message, should this represent:
a) The time you triggered Sync and the process completed (even though some failed)
b) The time all Sync endpoints synced successfully?

And maybe thirdly based on point 2 above, how does that impact the _Last Synced Timestamp_ shown on the device cc @dubdabasoduba  @ellykits

**Comment by joyce-x-chen** [comment] 2023-07-12 12:51
**Sync process**

What currently happens when syncing of an endpoint fails? It would be great to clarify and/or define:
- frequency of background sync (and from what starting point) when connected to internet 
    - e.g. every 15 minutes from completion of last sync attempt (regardless of sucess or failure) or at every quarter hour (i.e. at :00 :15 :30 :45) 
- number of retries when there is a failure to
    - sync an individual (client / event) record
    - sync an endpoint (all individual records related to _Patients_, _Encounters_, or _Observations_)
- what happens if the last retry fails? (the question @ndegwamartin asked)
    - does the entire sync process stop or does it continue on to the next endpoint? 
        - I think continuing to the next endpoint is preferable unless there is a technical reason you wouldn't want observations to sync before encounters

**Sync status messages**
- I recommend that the "Sync Complete" message only appears when all records sync successfully as @dubdabasoduba suggested (i.e. option B) 
- Can we come up with other Sync error messages for the other scenarios that provide more information about why sync has failed? @rowo @HenryRae 
    - [here](https://github.com/medic/cht-core/issues/3977) are some examples from Medic's CHT app
- We had implemented sync % completion and sync statistics pages in OpenSRP for some projects. In particular, I think sync % completion is super helpful because it's not binary. Sync incomplete might make a user panic/frustrated, but seeing Sync 90% complete might be reassuring to a user because it's indicated that sync is mostly successful

**Comment by ndegwamartin** [comment] 2023-07-12 15:02
Thanks for the feedback @joyce-x-chen.

On the frequency on sync, it is scheduled to happen every 15mins however, if a new sync finds an ongoing sync, the new sync attempt is discarded.

On the number of retries, the whole process is implemented as a single transaction thus the retry is configured for _x number_ of times if any endpoint/resource sync failure was encountered. This is configurable at the time of building the APK so could be different per flavor for example. the default is 3 times.

On the third point yeah the implementation is such that if one endpoint fails it proceeds to the next one. Only OpenSRP v1 required a certain order be maintained for data integrity.

**Comment by ndegwamartin** [comment] 2023-07-12 15:14
On the sync status messages we have some designs by the design team that provide more details and sync insights and will be on the roadmap once completed. Perhaps we could borrow some additional ideas from the link shared by Joyce. Additionally we can provide distinct sync insights for both _Upload_ and _Download_ sync, or maybe just a way to tell which of the sync is happening. cc @HenryRae @rowo 

For now [we have a simple implementation](https://github.com/opensrp/fhircore/pull/2492) in place to tell how may of each resource type remains un-synced on the device

**Comment by ndegwamartin** [comment] 2023-07-12 15:15
On the sync status messages, we have some designs by the design team that provide more details and sync insights and will be on the roadmap once completed. Perhaps we could borrow some additional ideas from the link shared by Joyce. 

Additionally we can provide distinct sync insights for both _Upload_ and _Download_ sync, or maybe just a way to tell which of the sync is happening cc @HenryRae @rowo 

For now [we have a simple implementation](https://github.com/opensrp/fhircore/pull/2492) in place to tell how many of each resource type remain un-synced on the device

**Comment by joyce-x-chen** [comment] 2023-07-12 15:53
> On the frequency on sync, it is scheduled to happen every 15mins however, if a new sync finds an ongoing sync, the new sync attempt is discarded.

@ndegwamartin when does the 15 minute interval start? And is the sync frequency configurable? 

> For now [we have a simple implementation](https://github.com/opensrp/fhircore/pull/2492) in place to tell how many of each resource type remain un-synced on the device

This is really awesome! 

> Do we need to inform the user after every automated retry?

My opinion: no, only after the entire transaction fails

**Comment by ndegwamartin** [comment] 2023-07-12 16:24
Sound like in the context of the scope of the original issue we are aligned on only showing **Sync Complete** once all resources are successfully synced. I will go ahead and implement this.

**Comment by AnnieMungai** [comment] 2023-07-12 17:21
@ndegwamartin if sync fails - can we add the different reasons for the failure? Example
Sync failed- no internet connection.
Sync failed - XYZ other reason. Can we know the reasons for sync failure and give brief instructions on what the user should do?

**Comment by samkanga** [comment] 2023-07-13 04:49
@ndegwamartin  @dubdabasoduba  My thoughts are:
1. I am in support of having one sync outcome notification to the user when sync is successful or fails. The `insights` section will server to know what specific items passed/failed sync. 
2. I also support posting the `Sync Completed` only when all the end points have successfully synced and providing the `Sync Failed` when a specific end point fails. 
3. It would also be great to have an overall sync percentage for the user. There are moments when a user does not know how much longer they should wait for sync to complete especially in the initial sync and the drawer menu is usually inaccessible.

**Comment by ndegwamartin** [comment] 2023-07-13 06:52
@samkanga for No. 3 we were able to fix the [sync reset to 0% bug](https://github.com/opensrp/fhircore/issues/2570) so now the progress you see is the actual percentage for the initial sync download.

**Comment by ndegwamartin** [comment] 2023-07-17 09:32
What is the expected behaviour for the app in between initial downward sync retries? 

**Scenario:** App attempts to sync and fails on one of the endpoints so retries again. Same for all the 3 retries. 

Whenever we do the initial data sync the user is blocked from using the app to do anything else. 

Should we block the user from using the app across all retries as long as the initial data sync was un-successful? Or just the first sync attempt as we retry the others in the background?

**Comment by samkanga** [comment] 2023-07-17 11:39
> Should we block the user from using the app across all retries as long as the initial data sync was un-successful? Or just the first sync attempt as we retry the others in the background?

@ndegwamartin I am in support of blocking the app use until we get a successful sync retry or manual sync. We are bound to run into more issues if we allow user to proceed without a successful initial sync or sync retry. These would include: 
1. Chance of creating duplicates in cases where a patient details cannot be found.
2. Missing tasks where generated tasks are part of the details not synced down.

**Comment by pld** [comment] 2023-07-17 17:01
@ndegwamartin removing the 0.2.4 label, since this is now in 0.2.4, we can close this with a PR that gets it into main

**Closed** 2023-07-18 19:01 UTC
Labels: Bug Report, Remote Sync

**Comment by Gental-Giant** [comment] 2023-07-20 10:51
@ndegwamartin I second Sam on blocking access until there's a complete and successful sync. i.e all the resources have been sync'd

**Comment by ndegwamartin** [comment] 2023-07-20 11:25
@Gental-Giant @samkanga tracking your recommendation here https://github.com/opensrp/fhircore/issues/2606

**Comment by AnnieMungai** [comment] 2023-07-31 13:13
0.25rc2- gateway

-LGTM!
