### ISSUE TITLE
App crashes for QuestionnaireResponse for Test Results Photo Capture

### ISSUE THREAD

**Issue by maimoonak** [opensrp/fhircore#908] opened 2021-12-29 14:12 UTC
**Describe the bug**
Test Result photo capture throws exception of unsupported data type

**To Reproduce**
1. Go to  Quest
2. Open Patient with for Test Results Photo Capture
3. OR fill a new one if not exists
4. Click on QuestionnaireResponse
5. App crashes

```
    kotlin.NotImplementedError: Question type ATTACHMENT not supported.
        at com.google.android.fhir.datacapture.QuestionnaireItemAdapter.getItemViewTypeMapping$datacapture_release(QuestionnaireItemAdapter.kt:129)
        at com.google.android.fhir.datacapture.QuestionnaireItemAdapter.getItemViewType(QuestionnaireItemAdapter.kt:104)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6367)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
```

**Comment by FikriMilano** [comment] 2021-12-29 14:27
@maimoonak I think this is a duplicate of #864

**Closed** 2021-12-29 14:37 UTC
Labels: bug
