### ISSUE TITLE
Family member not showing when added to a family

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1253] opened 2022-05-02 17:10 UTC
eCBIS v0.0.5
**Describe the bug**
when a family member is added to a family, the name of the family member does not show on the family profile. For this to show, the user must first exit the family profile and go back in. This is not the correct function. 

**To Reproduce**
1. On the application, navigate to any family already registered and register a new family member of any age. 
2. Save the form once you fill out the details and observe. The new household member is not on the list of household members. 
3. Now tap back from the family profile to the family list. 
4. From the family list, tap on the family again, now you see the family member that was added. 

**Acceptance Criteria**
- [ ] When you register a family member on an already existing family or create a new family and register a family member, once the registration form is saved, the user is navigated to the family profile. 
- [ ] The name of the newly registered family member is on the list of other family members. 
Note! The user does not need to navigate out of the family profile to view a newly registered member!

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by dubdabasoduba** [comment] 2022-05-03 09:16
This is caused by some missing states. If you go back to the main family register then back to the family the family member will appear. This means the Family profile is not refreshed after every family member's addition.

**Comment by charlene-570** [comment] 2022-05-18 12:13
@AnnieMungai 
Retest results from this 

Steps to retest

1.Log in APP
2.Add Family member under  a registered Family i.e Elon Musk Family
3.Confirm new added member is listed under the Family(Elon Musk Family)
4.Click on the back icon and select the Family member 
5.Confirm the added family is listed under the registered
![Screenshot_20220518-150550](https://user-images.githubusercontent.com/85434942/169036004-84496b35-b4b2-43ef-ab02-68e2c1bea786.png)
 family

Expected results 

The added family member should appear on the registered family list

See Screenshot attached

**Comment by ellykits** [comment] 2022-05-23 09:03
This was resolved in the latest ecbis release [v0.0.6-ecbis-rc1](https://github.com/opensrp/fhircore/releases/tag/v0.0.6-ecbis-rc1)

**Closed by ellykits** 2022-05-23 09:03 UTC
Labels: Bug Report, Quest, eCBIS
