### ISSUE TITLE
[Remote Sync] Hook up FHIR core with the sync strategies on the Gateway

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2042] opened 2023-02-12 22:56 UTC
**Describe the enhancement**
- We recently built a couple of plugins on the FHIR Acess Proxy project.  These plugins would help us authenticate, authorize and filter data based on the user assignments. 
- We are at a point where we can test plugins. 

**Implementation**
- [x] Deploy and test the latest Access Proxy updates. 
- [x] Try out the Acces proxy on FHIR core. 

**Acceptance criteria**
- [x] FHIR Core should be able to authenticate and authorize it's users via the Access Proxxy
- [x] Users should only sync down data that is tied to their assignments.

**Comment by ndegwamartin** [comment] 2023-02-13 08:28
**Updates on the FHIR Core Sync strategy implementation end to end**
- Set up test user with test roles, location and team
- Stage server deployment via Kubernetes for testing
- Confirmed filtered GET requests works - tested a filtered fetch on _Patient_ resource by _Organization_ via _Postman_

**Next steps:** 
- [ ] Patch required to exclude certain endpoints from access checker  [#2043](https://github.com/opensrp/fhircore/issues/2043)
- [ ] Set up demo data

**Comment by ndegwamartin** [comment] 2023-02-14 07:19
#2043 closed by [PR 14](https://github.com/opensrp/fhir-access-proxy/pull/14/commits/66db5f84ae7903ae175bc73492dd314b2f394894) and [PR 6599](https://github.com/onaio/infrastructure/pull/6599)

**Comment by ndegwamartin** [comment] 2023-03-15 12:07
Demo data set up by @dubdabasoduba  https://github.com/opensrp/fhir-resources/pull/1013

**Comment by ekigamba** [comment] 2023-06-27 14:55
I can confirm that I can register a new family on the device, sync, clear app data, login and sync to get the family again on a fresh install.

I used:
1. URL - https://fhir-access-proxy.smartregister.org/
2. Username: ecbis
2. App id: app/debug
3. Oauth client ID: fhir-core-client on stage keycloak

However, user `devtest` does not sync any data because they are not assigned to any location, careteam or organisation

**Comment by ndegwamartin** [comment] 2023-06-29 07:23
After performing the user management _(including Locations management and Team assignment)_ for this user `devtest`, the data synced down successfully. We can now close this cc @dubdabasoduba

**Closed by ndegwamartin** 2023-06-29 07:23 UTC
Labels: Enhancement, Remote Sync, Performance (App or Server), Ready for Engineering, Proxy Server
