### ISSUE TITLE
[Quest] Add the ability to mark Tasks as Complete or In progress

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1702] opened 2022-09-28 19:16 UTC
**Enhancement context**
- Currently, once a QuestionnaireResponse is created from a Questionnaire tied to a task we mark the task as complete. 
- We would like to update this to use the QuestionnaireResponse status to determine the Task status. 

**Implementation**
- [x] Write a method to check the `QuestionnaireResponse.status` in order to decide the `Task.status`.
    - [x] If the `QuestionnaireResponse.status` is `In Progress` then set the `Task.status` to `In Progress`
    - [x] If the `QuestionnaireResponse.status` is `Completed` then set the `Task.status` to `Completed`

**Acceptance Criteria**
- [ ] The completed task status should be determined by the status of the `QuestionnaireResponse.status` for the Questionnaire the Task's open. 

**Pre-requisite** 
- https://github.com/opensrp/fhircore/issues/1631

**Comment by dubdabasoduba** [comment] 2022-11-08 15:32
> @dubdabasoduba The work is done based on requirement in PR #1818. However, I do not see questionnaire-response status being set to COMPLETED any where. Although In progress is set on some action. Just wanted to inquire at what point this should be set? Task status should only be updated on in-progress / completed.

The QRs were always set as complete by default. The expectation was we either add the `in-progress` or `complete` status depending on how the questionnaire was closed. 

@allan-on was this the case with the `in-progress` work?

**Comment by allan-on** [comment] 2022-11-09 07:50
Hi @dubdabasoduba 
> @allan-on was this the case with the in-progress work?
Yes, the QuestionnaireResponse would be set as `in-progress` when navigating away from or closing the questionnaire screen prior to completing and submitting.

**Comment by maimoonak** [comment] 2022-11-09 08:46
@dubdabasoduba The PR https://github.com/opensrp/fhircore/pull/1818 is ready for review. I confirmed that in new implementation does not set it complete, rather it is null. I have handle null response.status as complete, because if response.status is not set it by default means that it is final, and complete.

**Closed** 2022-11-09 11:57 UTC
Labels: enhancement, Ready for Engineering, Health Task Workflow
