### ISSUE TITLE
[Quest] - Add Config page to set Server URL and other 1st time config credentials 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1376] opened 2022-06-27 08:45 UTC
**Description** 
Add a config page on Quest to be able to change the config URL endpoints to tweak e.g. 
1. Server URL to which the app should point to 
2. Change any other configs that the app may need to work appropriately based on the desired workflow 

NB. 
1. This requires more discussion and scoping. This is also based on the previous OpenSRP offerings 
2. May require new design to support it based on the unified design language

**Comment by f-odhiambo** [comment] 2022-06-27 09:59
CC @dubdabasoduba @ellykits @maimoonak

**Comment by pld** [comment] 2022-06-27 14:15
Cool, I think this makes sense, you would also need to be able to disable this config screen from the app config, eg many clients will not want their users to be able to adjust this.

**Comment by dubdabasoduba** [comment] 2022-06-30 07:54
@f-odhiambo This is a duplicate of this https://github.com/opensrp/fhircore/issues/1332

**Closed** 2022-06-30 08:07 UTC
Labels: sync, discussion, Quest
