### ISSUE TITLE
[Quest/Malawi Core] Patient resources being stored on server with missing attributes

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1510] opened 2022-08-06 07:58 UTC
**Describe the bug**
When you register a Patient and sync their details to the server, their details are stored without the 'generalPractitioner' and 'managingOrganization' attributes. As a result, if you clear the data, sign in and sync, those patients are not visible in the app.

**To Reproduce**
1. Go to the patients register
2. Click on register new person
3. Complete the registration process
4. Perform a sync
5. Check the server for the most recent patient added

**Expected behavior**
I expect these two attributes to added when [this](https://github.com/opensrp/fhircore/blob/e3413adb260c7c07e80cffaefba249497d88dd69/android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModel.kt#L163) function and [this](https://github.com/opensrp/fhircore/blob/e3413adb260c7c07e80cffaefba249497d88dd69/android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModel.kt#L174) function are called.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
Here is a sample of a patient who is visible in the app:

```
{
                "resourceType": "Patient",
                "id": "cac20d2c-6ec7-41c0-8cf7-cff9ee02701e",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-07-13T01:46:10.395+03:00",
                    "source": "#wz9njaAAAMnIHt6Y",
                    "tag": [
                        {
                            "system": "https://d-tree.org",
                            "code": "newly-diagnosed-client",
                            "display": "Newly Diagnosed Client"
                        }
                    ]
                },
                "active": true,
                "name": [
                    {
                        "family": "Wombach",
                        "given": [
                            "Abby"
                        ]
                    }
                ],
                "gender": "female",
                "birthDate": "1995-07-13",
                "address": [
                    {
                        "use": "home",
                        "type": "physical",
                        "district": "Blantyre"
                    }
                ],
                "generalPractitioner": [
                    {
                        "reference": "Practitioner/649b723c-28f3-4f5f-8fcf-28405b57a1ec"
                    }
                ],
                "managingOrganization": {
                    "reference": "Organization/10173"
                }
            }
```

**Comment by AbdulWahabMemon** [comment] 2022-08-15 07:20
The issue is fixed with updating these two json 
- form-configuration "form-saa-dev" with registration questionnaire new identifier
- registration-questionnaire with chw practitioner ids

@KhumboLihonga , @f-odhiambo

**Closed** 2022-08-26 12:00 UTC
Labels: Malawi CORE
