### ISSUE TITLE
HAPI FHIR next URL is broken

### ISSUE THREAD

**Issue by Wambere** [opensrp/fhircore#1714] opened 2022-10-04 14:02 UTC
**Describe the bug**
I am attempting to pull Fhir resources incrementally using the "next url" provided on the page response. This link however breaks and is not working as expected

**To Reproduce**

1. First request I make to  `https://ecbis-preview.smartregister.org/fhir/Group`
The response link is :
```
    "link": [
        {
            "relation": "self",
            "url": "https://ecbis-preview.smartregister.org:443/fhir/Group"
        },
        {
            "relation": "next",
            "url": "https://ecbis-preview.smartregister.org:443/fhir?_getpages=bbeb1d4f-a68c-482a-8f0f-dc64897c1ce7&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
        }
    ]
```
Notice the 443 added to the url

2. Second request is then to:  `https://ecbis-preview.smartregister.org:443/fhir?_getpages=bbeb1d4f-a68c-482a-8f0f-dc64897c1ce[…]set=20&_count=20&_pretty=true&_bundletype=searchset`
The response link is:
```
"link": [
        {
            "relation": "self",
            "url": "https://ecbis-preview.smartregister.org:443:443/fhir?_getpages=bbeb1d4f-a68c-482a-8f0f-dc64897c1ce7&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
        },
        {
            "relation": "next",
            "url": "https://ecbis-preview.smartregister.org:443:443/fhir?_getpages=bbeb1d4f-a68c-482a-8f0f-dc64897c1ce7&_getpagesoffset=40&_count=20&_pretty=true&_bundletype=searchset"
        },
        {
            "relation": "previous",
            "url": "https://ecbis-preview.smartregister.org:443:443/fhir?_getpages=bbeb1d4f-a68c-482a-8f0f-dc64897c1ce7&_getpagesoffset=0&_count=20&_pretty=true&_bundletype=searchset"
        }
    ]
```
Notice an extra 443 added to the next url 

3. Third request fails to the next url above fails with a 443

**Expected behavior**
My expectation is that the base url remains the same, that is `https://ecbis-preview.smartregister.org/fhir/Group` 
Then extra params are added at the end of that to pull in the next page

**Comment by pld** [comment] 2022-10-04 14:50
does this happen on stage or just ecbis preview?

feels like this could be a proxy/load balancer/forwarding issue not an actual server issue, but I'm not sure

@dubdabasoduba have we done any customization that might cause this?

**Comment by Wambere** [comment] 2022-10-24 06:35
@dubdabasoduba do we have a timeline on when this will be done?

**Comment by dubdabasoduba** [comment] 2023-01-05 18:36
I think the issue is happening with the Keycloak authenticated servers

**Comment by rehammuzzamil** [comment] 2023-01-30 22:21
Hi @dubdabasoduba , 
The issue is non-reproducible at my end (Local Machine).

Here are the details of the steps taken:
1. First request I make to http://localhost:8090/fhir/Group
The response link is :
`"link": [
        {
            "relation": "self",
            "url": "http://localhost:8090/fhir/Group"
        },
        {
            "relation": "next",
            "url": "http://localhost:8090/fhir?_getpages=7915357d-f94f-4444-8605-deae7e1d0639&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
        }
    ]`

Here 8090 is the port where server application is deployed.

2. Second request is then to: http://localhost:8090/fhir?_getpages=7915357d-f94f-4444-8605-deae7e1d0639&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset
The response link is:

` "link": [
        {
            "relation": "self",
            "url": "http://localhost:8090/fhir?_getpages=7915357d-f94f-4444-8605-deae7e1d0639&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
        },
        {
            "relation": "next",
            "url": "http://localhost:8090/fhir?_getpages=7915357d-f94f-4444-8605-deae7e1d0639&_getpagesoffset=40&_count=20&_pretty=true&_bundletype=searchset"
        },
        {
            "relation": "previous",
            "url": "http://localhost:8090/fhir?_getpages=7915357d-f94f-4444-8605-deae7e1d0639&_getpagesoffset=0&_count=20&_pretty=true&_bundletype=searchset"
        }
    ]`

Please note, no extra port was added to the next URL.

@Wambere Please let me know if you are still encountering the same issue. 

cc: @dubdabasoduba @f-odhiambo

**Comment by dubdabasoduba** [comment] 2023-02-08 13:38
This is now fixed.

**Closed by dubdabasoduba** 2023-02-08 13:38 UTC
Labels: Bug Report, Server Side

**Comment by ndegwamartin** [comment] 2023-02-08 13:42
@dubdabasoduba  I think there was a team in the FHIR SDK call that were facing the same (or similar) issue - is there a brief summary we can document here on the fix we made?

**Comment by dubdabasoduba** [comment] 2023-02-09 00:20
The upgrade to v6 fixed it.
